services:
    # Production service
    nextjs:
        build:
            context: .
            dockerfile: Dockerfile
            target: runner
        ports:
            - "3000:3000"
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: brainai
        depends_on:
            - mysql

    # Development service (hot reloading, live code sync)
    nextjs-dev:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        ports:
            - "3001:3000" # Container still listens on 3000, mapped to host port 3001
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: brainai
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        volumes:
            - todo-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: brainai

    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: secret

volumes:
    todo-mysql-data:
